x = 10
y = 3
z = 2
print ("x =",x)
print ("y =",y)
print ("z =",z)
hasil = x + y
print ("x + y =",hasil)
hasil = x - y
print ("x - y =",hasil)
hasil = x * y
print ("x * y =",hasil)
hasil = x / y
print ("x / y =",hasil)
hasil = x % y
print ("x % y =",hasil)
hasil = x // y
print ("x // y =",hasil)
hasil = x ** y
print ("x ** y =",hasil)
hasil = (x+y)*z
print ("(x + y) * z =",hasil)
hasil = x + y * z
print ("x + y * z =",hasil)